// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var app = document.querySelector("#root");

if (!(app == null)) {
  ReactDom.render(React.createElement(App.make, {}), app);
}

export {
  
}
/* app Not a pure module */
